# Generated by Django 3.2 on 2021-12-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand_name',
            options={'verbose_name': 'Brand Name', 'verbose_name_plural': 'Brand Names'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='model_name',
            options={'verbose_name': 'Model Name', 'verbose_name_plural': 'Model Names'},
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_code', models.CharField(max_length=300, unique=True)),
                ('image', models.URLField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='mobile.brand_name')),
            ],
        ),
    ]
