# Generated by Django 3.2 on 2021-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_mobile_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='color',
            field=models.ManyToManyField(blank=True, to='mobile.Color'),
        ),
    ]
