# Generated by Django 3.2 on 2021-12-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_mobile_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='color',
        ),
        migrations.AddField(
            model_name='mobile',
            name='color',
            field=models.OneToOneField(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='mobile.color'),
            preserve_default=False,
        ),
    ]
