# Generated by Django 3.2 on 2021-12-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20211225_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='brand_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='mobile.brand_name'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='mobile.model_name'),
        ),
    ]
