# Generated by Django 3.2 on 2021-12-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_auto_20211225_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'Mobile Phone', 'verbose_name_plural': 'Mobile Phones'},
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='color',
        ),
        migrations.AddField(
            model_name='mobile',
            name='color',
            field=models.ManyToManyField(to='mobile.Color'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='model_name',
            name='model_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
