# Generated by Django 3.2 on 2021-12-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0010_auto_20211226_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_color', to='mobile.color'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
