# Generated by Django 3.2 on 2021-12-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_alter_mobile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_color', to='mobile.color'),
        ),
    ]
